name: skripsi_v2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  get_storage: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  logger: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: 2.15.0
  firebase_auth: 4.7.2
  cloud_firestore: 4.8.4
  firebase_storage: 11.2.5
  flutter_downloader: 1.11.1
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/images/Logo HIMTIF.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - asset/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto-Black.ttf
          weight: 900
        - asset: asset/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: asset/fonts/Roboto-Light.ttf
          weight: 300
        - asset: asset/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: asset/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: asset/fonts/Roboto-Thin.ttf
          weight: 100

